### PR TITLE
Fix for Blender 3.2

### PR DESCRIPTION
**Pull request by silentrald**
Fixed tile palette selection and tile painting

### CODE REVIEW

**Comment by ajbaldocchi** [comment]
See #137 and #140

**Comment by silentrald** [comment]
Should I close this then since this might be a redundant fix?

**Comment by TheBricktop** [comment]
Ive tried Your fix but im getting error whenever im trying to resize the tile palette, 
obraz
Blender 3.2.2

**Comment by silentrald** [comment]
Looking at the bug, you just have to cast the `display_offset.x` to an int by reading from exception you gave me. Also in the code you have to cast the `display_offset.y` below it as well.

**Pull request closed without merging**
